version: '3'
services:
  traffic-mysql:
    container_name: traffic-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: traffic_generator
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    restart: always

  app:
    container_name: traffic-back
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - 8081:8080
    command: mvn clean spring-boot:run
    depends_on:
      - traffic-mysql
    restart: on-failure